config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/new'
  devise_for :users

  root to: 'items#index'
  resources :items do
    resources :itemsends
  end
  # resources :buylogs
  # resources :itemsends
  
  # resources :items do
  #   resources :orders , only: [:index, :create]
  # end
end

app/models/itemsend.rb
class Itemsend < ApplicationRecord
  belongs_to :buylog
end

app/controllers/itemsends_controller.rb
class ItemsendsController < ApplicationController
  before_action :authenticate_user!,only: [:new, :create,:edit]
  before_action :p_id_find
  before_action :set_souldout
  before_action :my_item_check

  def new
    p_id_find
    @item = BuylogItemsend.new
  end
  def create 
    p_id_find
    @price = @items.price
    @item = BuylogItemsend.new(item_params)
    if @item.valid?
      pay_item
      @item.save      
      redirect_to root_path
    else
        render :new
    end
  end

  private

  def item_params
    params.require(:buylog_itemsend).permit(:cdata,:exp_month,:exp_year,:cvc,:postalcode,
    :prefecture_id,
    :city,:cityaddress,
    :buildingname,
    :sendtel).merge(item_id: params[:item_id],user_id: current_user.id,token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: @price,  # 商品の値段
      card: params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類（日本円）
    )
  end

  def set_souldout
    if p_id_find.buylog != nil
        @items = Item.all.order("created_at DESC")
        render "items/index"
    end
  end

  def my_item_check

    if current_user.id == p_id_find[:user_id]
        @items = Item.all.order("created_at DESC")
        render "items/index"
    end
  end

  def p_id_find
    @items = Item.find(params[:item_id])
  end  
end

app/helpers/itemsends_helper.rb
module ItemsendsHelper
end

app/views/itemsends/new.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @items.image  ,class: 'buy-item-img' %>
      <%#= image_tag @items.image ,class:"item-box-img" %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @items.productname %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @items.price %></p>
          <p class='item-price-sub-text'><%= @items.shippingcharge.name %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @items.price %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%#= form_with model: @item, mehod: :post,id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%= form_with model: @item,url: item_itemsends_path,mehod: :post,id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cdata, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :postalcode, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Shippingarea.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
        <%#= f.collection_select(:shippingarea_id, Shippingarea.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
        <%#= f.text_area :productname, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cityaddress, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :buildingname, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :sendtel, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn", id:"button" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>